### ISSUE TITLE
readme.md outdated

### ISSUE THREAD

**Issue by TomasKohout** [bfil/scala-automapper#12]
Hi, there is outdated readme. There is change in functions' name. dynamicallyTo is changed to applyDynamicallyNamed. Use of this function also differs from dynamicallyTo. 

Can you change it please?

**Comment by bfil** [comment]
The API didn't change, `dynamicallyTo` is the method you should be using, it is just enabled using a dynamic invocation under the hood.

The method `applyDynamicNamed` is part of Scala's [Dynamic API](https://www.scala-lang.org/api/current/scala/Dynamic.html), which is used by the Automapper to allow passing an arbitrary number of named parameters that will be checked by the macro at compile time when generating the mappings.

Hope this helps.

**Comment by TomasKohout** [comment]
Thanx a lot. 👍Idea is not able to resolve dynamicallyTo method and show it as if it didn't exist. That was my actual problem.

**Comment by bfil** [comment]
@TomasKohout yeah, it's an issue with IntelliJ's Scala plugin, more info here: https://github.com/bfil/scala-automapper/issues/3#issuecomment-343899184
