### ISSUE TITLE
Better alternative

### ISSUE THREAD

**Issue by Tamriel** [bfil/scala-automapper#13]
First, thank you for your work!
Since I had the same problems as #11, I searched for alternatives and found [chimney](https://github.com/scalalandio/chimney).
It has the same features but is more powerful and more mature.

**Comment by bfil** [comment]
Thanks for the feedback! I've tried to fix that issue but haven't managed to come up with a way to get the fully qualified path for companion object of classes in my macro (which is what is causing the issue I believe), I might try again when I have some time.

Could you add this as a comment on the issue itself? I'll close this as it doesn't really qualify as an issue. Thanks!
