### ISSUE TITLE
Are there plans to support Scala 2.13?

### ISSUE THREAD

**Issue by jeffrey-aguilera** [bfil/scala-automapper#14]

**Comment by bfil** [comment]
Yes, I will publish it for Scala 2.13 as soon as I have some free time.

**Comment by bfil** [comment]
@jeffrey-aguilera it was more straightforward than I thought, not a lot of changes to the Scala API in version 2.13. I've released version `0.7.0` if you want to try it out.

**Comment by jeffrey-aguilera** [comment]
Thank you, sir. It works brilliantly.
