### ISSUE TITLE
Support polymorphic types

### ISSUE THREAD

**Issue by mkotsbak** [bfil/scala-automapper#2]
Support for mapping polymorphic types, e.g:

trait A
case class B extends A
case class C extends A

trait D
case class E extends D
case class F extends D

Then A should be mappable to D. Probably it must be supplied mapping rules between each of the sub class pairs.

**Comment by nikitapecasa** [comment]
There is another solution to this problem that doesn't require changes in the library:
 add an implicit conversion from trait A to trait D to scope where you call mapping generation macro.

```scala
sealed trait A
object A {
  case object A1 extends A
  case object A2 extends A
}
sealed trait B
object B {
  case object B1 extends B
  case object B2 extends B
}
case class Source(a: A)
case class Target(a: B)

implicit def aToB(a: A): B = a match {
  case A.A1 => B.B1
  case A.A2 => B.B2
}

import io.bfil.automapper._

automap(Source(A.A1)).to[Target]
```

**Comment by mkotsbak** [comment]
Nice!

**Comment by mkotsbak** [comment]
Maybe it should be added to the documentation?

I guess you would need `automap(Source(A.A2)).to[Target]` also?

**Comment by nikitapecasa** [comment]
Sorry, don't get your question.
But this is just an example of using automap after you defined an implicit conversion.

```scala
automap(Source(A.A1)).to[Target] == Target(B.B1) // true
automap(Source(A.A2)).to[Target] == Target(B.B2) // true
```

**Comment by bfil** [comment]
I'm closing this issue since this is somewhat supported and there are examples in the tests on how to achieve this.
