### ISSUE TITLE
Make scalatest a test dependency

### ISSUE THREAD

**Issue by avonheimburg** [bfil/scala-automapper#5]
Right now, project/Build.scala pulls in scalatest as a regular dependency. That leads to scalatest being included in the (test) build of a project that uses automapper. That can be confusing if you are using a different framework yourself, as `sbt test` will report that scalatest has found no tests.

Please simply make scalatest a  `% test` dependency.

**Comment by bfil** [comment]
Damn, you're absolutely right. Will amend asap.

**Comment by bfil** [comment]
Fixed in version`0.5.0` (https://github.com/bfil/scala-automapper/commit/2ed491293e753ed6d0115c918906f516c82e43b3)

**Comment by avonheimburg** [comment]
Thank you!
